# Generated by Django 3.2.6 on 2021-11-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='output',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
